### ISSUE TITLE
Failing validators/policies on-chain do not reflect on tests

### ISSUE THREAD

**Issue by hyphenrf** [mlabs-haskell/plutip#74]
- create a new project via plutus-scaffold, remove `?rev=<hash>` field from plutip to track master.
- write a simple validator that always fails.
- run its endpoint via `assertExecution` with `shouldFail`
- the test does not follow expectations, instead, the contract succeeds

Is this the intended behaviour? i.e. does plutip only catch contract errors and no onchain errors?

**Comment by mikekeke** [comment]
> write a simple validator that always fails.
run its endpoint via assertExecution with shouldFail

@hyphenrf maybe I'm missing something, but if validator always fails, then asserting execution with `shouldFail` should succeed, as failure is expected behavior signaled by `shouldFail` - contrary to `shouldSucceed`.  When `shouldSucceed` is used for contract with validator that always fails - it will fail the test.

**Comment by hyphenrf** [comment]
wording is hard
![image](https://user-images.githubusercontent.com/26802762/171359057-a26e1f2d-436c-4c58-9963-da13661f8097.png)

**Comment by mikekeke** [comment]
@hyphenrf 
`main` branch now has case with validator that always fails:
[on- and off-chain code](https://github.com/mlabs-haskell/plutip/blob/master/test/Spec/TestContract/AlwaysFail.hs)
[test case](https://github.com/mlabs-haskell/plutip/blob/master/test/Spec/Integration.hs#L195-L203)
It fails as expected.

Does this case looks something like you were running with `assertExecution` and `shouldFail`?

**Comment by hyphenrf** [comment]
oh I should've closed this, yeah it turned out the problem was in my understanding of _when_ a validator executes, signaling failure.
Thanks for the test-case :heart:
